[package]
name = "ibus-vie-im"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Input method FSM for Vietnamese (Telex, VNI, VIQR)"

[dependencies]
ibus-vie-vi = { path = "../ibus-vie-vi" }

[dev-dependencies]
insta.workspace = true
